[global]
accounts = o365_1

[o365_1]
maildir = ~/maildir/o365_1
user = myuser@contoso.com
clientid = application-client-id
tenant = organizations
folderseparator = .
folderexclude = Journal,Notes,Calendar

